### PR TITLE
Update Profile to use IdName for hometown and location fields.

### PR DESCRIPTION
**Pull request by xsorifc28**
Since the Graph API only returns Id and name for a users current location and hometown, I think it makes sense to use just the IdName object. 

This also solves the issue of "Location" being misleading (Since it extended IdName & had physical location info).

Hometown is also not used anymore, and probably not required.

To get more info about a user's hometown or location, you must use `GetPage` with `getProfile().getHometown().getId()` or `getProfile().getLocation().getId()`.

Also attempting to fix an issue with U.S. zip codes, since they can contain strings. Some Facebook places have a "NNNN-NNNN", ZIP+4 zip code, and parsing this as an integer causes an exception.

### CODE REVIEW

**Comment by sromku** [comment]
@xsorifc28 Great fixes. I think that if `Hometown` is not referenced by any other classes, then it worth deleting it at all. wdyt?

**Comment by xsorifc28** [comment]
I deprecated it, but I think it can be deleted.

**Comment by sromku** [comment]
@xsorifc28 can you delete and update the PR? I will merge it after.
Much thanks!

**Comment by xsorifc28** [comment]
@sromku  Deleted.

**Comment by sromku** [comment]
@xsorifc28 Great work! Much thanks and very appreciated!

**Pull request merged**
